main: com.cavetale.race.RacePlugin
name: Race

author: StarTux
description: Racing Minigame
website: https://cavetale.com

version: 0.1
api-version: 1.18

depend: [Core, Mytems, Sidebar, WorldEdit, PlayerCache, WorldMarker, Fam]
softdepend: []

commands:
  race:
    aliases: [raceedit, raceadmin, redit]
    description: Race Command
    permission: race.admin
    usage: /race

permissions:
  race.admin:
    description: Use /race
    default: op
