main: com.cavetale.race.RacePlugin
name: Race

author: StarTux
description: Racing Minigame
website: https://cavetale.com

version: 0.1
api-version: 1.19

depend: [Core, Mytems, WorldMarker, Fam, Area]
softdepend: []

commands:
  racer:
    aliases: []
    description: Race Command
    permission: race.race
    usage: /race

  raceedit:
    aliases: [raceadmin]
    description: Race Admin Command
    permission: race.admin
    usage: /race

permissions:

  race.race:
    description: Use /race
    default: op

  race.admin:
    description: Use /raceadmin
    default: op
