main: com.cavetale.race.RacePlugin
name: Race

author: StarTux
description: Racing Minigame
website: https://cavetale.com

version: 0.1
api-version: '1.21'

depend:
- Core
- Mytems
- WorldMarker
- Fam
- Area
- Creative
- SQL
softdepend: []

commands:
  race:
    aliases: []
    description: Race Command
    permission: race.race
    usage: /race

  raceadmin:
    aliases: raceadm
    description: Race Admin Command
    permission: race.admin
    usage: /raceadm

  raceedit:
    aliases: []
    description: Race Edit Command
    permission: race.edit
    usage: /raceedit

permissions:

  race.race:
    description: Use /race
    default: op

  race.admin:
    description: Use /raceadmin
    default: op

  race.edit:
    description: Use /raceedit
    default: op
