main: com.cavetale.race.RacePlugin
name: Race
version: 0.1

author: StarTux
description: Racing Minigame
website: https://cavetale.com

api-version: 1.17

depend: [Mytems, Sidebar]
softdepend: []

commands:
  race:
    aliases: []
    description: Race Command
    permission: race.race
    usage: /race

permissions:
  race.race:
    description: Use /race
    default: op
